version: "3"
services:
  trasformer:
    container_name: transformer
    image: xaphere/xls-transformer:v0.0.1
    ports:
    - 8080:5000
  storage:
    container_name: storage
    image: xaphere/simple-storage-server:v0.0.1
    environment:
      - STORAGE=/storage
      - PORT=4000
    volumes:
      - ./data/originals:/storage
    ports:
      - 9000:4000